### PR TITLE
feat: revert get

### PR DESCRIPTION
**Pull request by peterpeterparker**

### CODE REVIEW

**Comment by peterpeterparker** [comment]
@sansan88 revert. I need a get to be able to go forward with my task and test it.

**Comment by sansan88** [comment]
Hmm you can introduce a new function or test it with pistman?

**Comment by peterpeterparker** [comment]
get was easier. I'm finish with this, you can revert to post if you would like. check with jonathan as he has to check the PDF.

**Comment by sansan88** [comment]
@peterpeterparker change back to a post call!

**Pull request merged**
