### PR TITLE
feat: add owllyId to PDF metadata

### PR DESCRIPTION
**Pull request by peterpeterparker**

### CODE REVIEW

**Comment by peterpeterparker** [comment]
cc @sansan88 

New function's URI: `https://europe-west6-project-owlly.cloudfunctions.net/generatePDF/:owllyId`

Result: Owlly ID is saved as a PDF metadata

Example:

URI: `https://europe-west6-project-owlly.cloudfunctions.net/generatePDF/mkro4noxKW9CNGE7mGFE`

Output: It downloads a PDF `mkro4noxKW9CNGE7mGFE.pdf`

Metadata:

> ❯ exiftool mkro4noxKW9CNGE7mGFE.pdf 
> ExifTool Version Number         : 11.70
> File Name                       : mkro4noxKW9CNGE7mGFE.pdf
> Directory                       : .
> File Size                       : 1356 bytes
> File Modification Date/Time     : 2020:10:10 09:42:44+02:00
> File Access Date/Time           : 2020:10:10 09:42:44+02:00
> File Inode Change Date/Time     : 2020:10:10 09:42:45+02:00
> File Permissions                : rw-r--r--
> File Type                       : PDF
> File Type Extension             : pdf
> MIME Type                       : application/pdf
> PDF Version                     : 1.3
> Linearized                      : No
> Page Count                      : 1
> Producer                        : PDFKit
> Creator                         : PDFKit
> Create Date                     : 2020:10:10 07:42:44Z
> Owlly Id                        : mkro4noxKW9CNGE7mGFE

**Comment by sansan88** [comment]
a userId would also be cool, so we can check if a user has signed a document twice.

**Comment by peterpeterparker** [comment]
here you've got the basics. enhance it as you need for the use case.

**Comment by sansan88** [comment]
awesome work!

**Comment by sansan88** [comment]
@jonarivado 

Checkout out this work of david! you can use it for your pdf method

**Pull request merged**
